/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blok.main;

import interfaces.ICore;
import interfaces.ISimulator;
import javax.swing.JOptionPane;
import themeFactory.AbstractThemeFactory;

/**
 *
 * @author sandroandrade
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow(ICore core) {
        m_core = core;
        initComponents(); 
        
        String themeName = (String) JOptionPane.showInputDialog(null, "Escolha um tema!", "Blok no javinha",
            JOptionPane.QUESTION_MESSAGE, null, m_core.getPluginController().getloadedPluginsNamesByType(AbstractThemeFactory.class).toArray(),"StandardFactory");
        if(themeName==null){
            System.exit(0);
        }
        String simulatorName = (String) JOptionPane.showInputDialog(null, "Escolha um simulador de fisica!", "Blok no javinha",
            JOptionPane.QUESTION_MESSAGE, null, m_core.getPluginController().getloadedPluginsNamesByType(ISimulator.class).toArray(),"StandardFactory");
        if(simulatorName==null){
            System.exit(0);
        }
        m_core.getPluginController().loadTheme(simulatorName);
        m_core.getPluginController().loadTheme(themeName);       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    private ICore m_core;
}
