/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blok.main;

import interfaces.ICore;
import java.awt.Dimension;
import interfaces.IUIController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JMenuItem;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author sandroandrade
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow(ICore core) {
        m_core = core;
        initComponents();    
        
//        String[] plugins = m_core.getPluginController().loadedThemes();
//        for (int i = 0; i < plugins.length; i++){
//                jThemes.add(plugins[i]);
//        }
        loadMenuThemes();
    }
    
    public void loadMenuThemes() {
        jThemes.addMenuListener(new MenuListener() {

            @Override
            public void menuSelected(MenuEvent e) {
                String[] plugins = m_core.getPluginController().loadedThemes();
                for (int i = 0; i < plugins.length; i++) {
                   // jThemes.add(plugins[i]);
                    final String themeName = plugins[i];
                    jThemes.add(createMenuItem(plugins[i], new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent ae) {
                            m_core.getPluginController().loadTheme(themeName);
                        }
                    }));
                }
            }

            @Override
            public void menuDeselected(MenuEvent me) {
                jThemes.removeAll();          
            }

            @Override
            public void menuCanceled(MenuEvent me) {
            }
        });
    }

private JMenuItem createMenuItem(String nome, ActionListener actionListener) {
                JMenuItem item = new JMenuItem(nome);
                item.addActionListener(actionListener);
                return item;
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jThemes = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jThemes.setText("Themes");
        jMenuBar1.add(jThemes);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jThemes;
    // End of variables declaration//GEN-END:variables
    private ICore m_core;
}
